# Generated by Django 5.2.11 on 2026-02-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='image',
        ),
    ]
